---
#vpn-rtr-1:
#        hostname: 192.168.106.111 # hostname or IP address. Has to be a hostname if you wish to filter on device names.
#        platform: ios # Used to define device's platform for connection purposes & filtering (ios, iosxr, nxos, eos).
#        groups: # Used to assign the connection options defined in the groups.yaml file.
#          - cisco_ios_xe
#        data: # role & site data used for the filtering purposes. Can be anything
#          role: VPN
#          site: EVE
#
#vpn-rtr-2:
#        hostname: 192.168.106.112 # hostname or IP address. Has to be a hostname if you wish to filter on device names.
#        platform: ios # Used to define device's platform for connection purposes & filtering (ios, iosxr, nxos, eos).
#        groups: # Used to assign the connection options defined in the groups.yaml file.
#          - cisco_ios_xe
#        data: # role & site data used for the filtering purposes. Can be anything
#          role: VPN
#          site: EVE

devnetsandboxiosxe.cisco.com:
        hostname: devnetsandboxiosxe.cisco.com
        platform: ios
        groups:
          - cisco_ios_xe
        data:
          role: SANDBOX
          site: DEVNET